name: 'Blixten & Dunder'
favicon: null
layout_spectrum: 0.44098815764300525
typography_spectrum: 0.09827971155755222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7485693274065852
  lightness: 0.5679531244095415
  saturation: 0.3113258134108037
  rhythmicContrast: 0.0014265882782638073
purpose: []
